### ISSUE TITLE
Pipeline is not running in a branch

### ISSUE THREAD

**Issue by ClaudenirFreitas** [Robinson-Dev/users#15]
Pipeline is running only in the `main` branch. It's interesting to run the pipelines in others branches too.

**Comment by RobinsonCarvalho** [comment]
Claudenir, perhaps I did not get it right. I update the action to check if it would work and it did. What should I do in this situation?

**Comment by ClaudenirFreitas** [comment]
Ops, sorry man. I've just added a description. 😅

**Comment by RobinsonCarvalho** [comment]
Sorry? I've no mercy 🤼‍♂️.  You're the guy wearing green because it's your favorite team color 🤣

**Comment by RobinsonCarvalho** [comment]
At last I could make it work, Claudenir.

Thank you

**Comment by ClaudenirFreitas** [comment]
Cool, it's working as expected! 
Nice job man!
