### ISSUE TITLE
Add pipeline to run tests

### ISSUE THREAD

**Issue by ClaudenirFreitas** [Robinson-Dev/users#8]
## requirements
- [x] create pipeline to run tests using Github Actions;
- [x] add code coverage plugin;

**Comment by ClaudenirFreitas** [comment]
I didn't find the code coverage implementation, could you share it?

**Comment by RobinsonCarvalho** [comment]
Hello Claudenir,

Finally I managed to do it. Can you have a look, please, and tell me if it was what you expected?

Thank very much my friend

**Comment by ClaudenirFreitas** [comment]
That's amazing! Nice job man!
